import { useSafuu } from '@decentology/hyperverse-bsc-safuu/react';
import { useBSC } from '@decentology/hyperverse-bsc/react';
import { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
const Admin: NextPage = () => {
	const [isMounted, setIsMounted] = useState(false);
	const [status, setStatus] = useState({
		gold: false,
		white: false,
	});
	useEffect(() => setIsMounted(true), []);
	const { Connect } = useBSC();
	const {
		setGoldListSaleStatus,
		setWhiteListSaleStatus,
		isGoldListSaleActive,
		isWhiteListSaleActive,
	} = useSafuu();
	useEffect(() => {
		isGoldListSaleActive?.().then((x) => setStatus({ ...status, gold: x }));
		isWhiteListSaleActive?.().then((x) => setStatus({ ...status, white: x }));
	}, [isGoldListSaleActive, isWhiteListSaleActive, status]);
	const toggleGoldStatus = () => {
		setGoldListSaleStatus!(!status.gold).then(() => {
			setStatus({ ...status, gold: !status.gold });
		});
	};
	const toggleWhiteStatus = () => {
		setWhiteListSaleStatus!(!status.white).then(() => {
			setStatus({ ...status, white: !status.white });
		});
	};
	return (
		<div className={styles.container}>
			<Head>
				<title>SafuuX - Sample App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>Admin</h1>
				<p className={styles.description}>
					Get started by editing <code className={styles.code}>pages/admin.tsx</code>
					{isMounted && <Connect />}
				</p>
				{isMounted && (
					<>
						<div className={styles.grid}>
							<div className={styles.card}>
								<h2>Gold List</h2>
								<table>
									<tr>
										<td>Status:</td>
										<td>{String(status.gold)}</td>
									</tr>
								</table>
								<button onClick={toggleGoldStatus}>Toggle Status</button>
							</div>
						</div>
						<div className={styles.grid}>
							<div className={styles.card}>
								<h2>White List</h2>
								<table>
									<tr>
										<td>Status:</td>
										<td>{String(status.white)}</td>
									</tr>
								</table>
								<button onClick={toggleWhiteStatus}>Toggle Status</button>
							</div>
						</div>
					</>
				)}
			</main>
		</div>
	);
};

export default Admin;
