import { useBSC } from '@decentology/hyperverse-bsc/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { GoldListMint } from '../components/gold-list';
import { Statistics } from '../components/statistics';
import { WhiteListMint } from '../components/white-list';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	const [isMounted, setIsMounted] = useState(false);
	useEffect(() => setIsMounted(true), []);
	const { Connect } = useBSC();
	return (
		<div className={styles.container}>
			<Head>
				<title>SafuuX - Sample App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <span style={{ color: 'blueviolet' }}>SafuuX</span> App
				</h1>

				<p className={styles.description}>
					Get started by editing <code className={styles.code}>pages/index.tsx</code>
					{isMounted && <Connect />}
				</p>

				<div className={styles.grid}>
					<div className={styles.card}>
						<h2>Gold List</h2>
						<p>When the gold list is active you can mint SafuuX token</p>
						{isMounted && <GoldListMint />}
					</div>

					<div className={styles.card}>
						<h2>White List</h2>
						<p>When the white list is active you can mint SafuuX token</p>
						{isMounted && <WhiteListMint />}
					</div>

					<div className={styles.card}>
						<h2>Full Node Stats</h2>
						<p>Below are a list of statistics on the contract</p>
						{isMounted && <Statistics nodeType="full" />}
					</div>

					<div className={styles.card}>
						<h2>Lite Node Stats</h2>
						<p>Below are a list of statistics on the contract</p>
						{isMounted && <Statistics nodeType="lite" />}
					</div>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
