import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useStorage } from '@decentology/hyperverse-storage-ipfs';
import { useEffect } from 'react';
const Home: NextPage = () => {
	const { uploadFile, downloadFile, openFile, getLink } = useStorage();

	const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
		const file = event.target.files![0];
		const fileHash = await uploadFile(file);
		console.log(fileHash);
	};

	useEffect(() => {
		// (async () => {
		//     const image = await downloadFile('QmPyzeGXqVYCUg5mMyw7YeiNv3njkYhBaKXvL3dxRZ1Ln4');
		//     console.log(image);
		// })()
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://www.decentology.com">Hyperverse</a>
				</h1>

				<p className={styles.description}>
					Sample IPFS File upload and preview
					<code className={styles.code}>@decentology/hyperverse-storage</code>
				</p>

				<div>
					<h2>Upload File</h2>
					<div>
						<input type="file" id="file" onChange={handleFileUpload} />
					</div>
					<div>
						<Image
							src={getLink('QmPyzeGXqVYCUg5mMyw7YeiNv3njkYhBaKXvL3dxRZ1Ln4')}
							alt="My image"
							width="200"
							height="200"
						/>
					</div>
				</div>
				<code>
					https://cloudflare-ipfs.com/ipfs/QmPyzeGXqVYCUg5mMyw7YeiNv3njkYhBaKXvL3dxRZ1Ln4
				</code>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
