import { Blockchain, useHyperverse } from '@decentology/hyperverse';
import { useEthereum } from '@decentology/hyperverse-ethereum';
import { useFlow } from '@decentology/hyperverse-flow';
import { useMetis } from '@decentology/hyperverse-metis';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useContext } from 'react';
import context from '../context/globalContext';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	const { blockchain } = useHyperverse();
	const { address, connect: EthereumConnect, disconnect: EthereumDisconnect } = useEthereum();
	const {
		address: metisAddress,
		connect: MetisConnect,
		disconnect: MetisDisconnect,
	} = useMetis();
	const { user, authenticate, unauthenticate } = useFlow();
	const globalContext = useContext(context);
	switch (blockchain!.name) {
		case Blockchain.Ethereum:
			var connect = EthereumConnect;
			var disconnect = EthereumDisconnect;
			break;
		case Blockchain.Metis:
			var connect = MetisConnect;
			var disconnect = MetisDisconnect;
			break;
		case Blockchain.Flow:
			var connect = authenticate;
			var disconnect = unauthenticate;
			break;
		default:
			break;
	}
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Image src="/H-LOGO-DARK-BLUE.png" alt="Hyperverse Logo" width={335} height={64} />
				<h1 className={styles.title}>
					<span style={{ color: 'teal' }}>Multi Chain</span> Test
				</h1>
				<h2>Blockchain</h2>
				<p>{blockchain?.name}</p>
				<h2>Address</h2>
				<ul>
					<li>Etheruem: {address}</li>
					<li>Metis: {metisAddress}</li>
					<li>Flow: {user?.addr}</li>
				</ul>
				<div className={styles.grid}>
					<div onClick={() => connect()} className={styles.card}>
						<h2>Connect</h2>
						<p>Connect wallet to the selected provider</p>
					</div>

					<div onClick={() => disconnect()} className={styles.card}>
						<h2>Disconnect</h2>
						<p>Disconnect wallet from selected provider</p>
					</div>

					<div
						onClick={() => globalContext?.switchBlockchain('ethereum')}
						className={styles.card}
					>
						<h2>Switch to Ethereum</h2>
						<p>Switch to the Ethereum blockchain wallet provider</p>
					</div>
					<div
						onClick={() => globalContext?.switchBlockchain('metis')}
						className={styles.card}
					>
						<h2>Switch to Metis</h2>
						<p>Switch to the Metis blockchain wallet provider</p>
					</div>

					<div
						onClick={() => globalContext?.switchBlockchain('flow')}
						className={styles.card}
					>
						<h2>Switch to Flow</h2>
						<p>Switch to the Flow blockchain wallet provider</p>
					</div>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src="/H-LOGO-DARK-BLUE.png"
							alt="Hyperverse Logo"
							width={84}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
